AshAvalanche/ash-rs

- Cargo.lock
- Cargo.toml
- crates/ash_cli/src/avalanche/subnet.rs
- crates/ash_cli/src/avalanche/validator.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/Cargo.toml
- crates/ash_sdk/conf/default.yml
- crates/ash_sdk/src/avalanche.rs
- crates/ash_sdk/src/avalanche/blockchains.rs
- crates/ash_sdk/src/avalanche/jsonrpc.rs
- crates/ash_sdk/src/avalanche/jsonrpc/info.rs
- crates/ash_sdk/src/avalanche/jsonrpc/platformvm.rs
- crates/ash_sdk/src/avalanche/nodes.rs
- crates/ash_sdk/src/avalanche/subnets.rs
- crates/ash_sdk/src/errors.rs
- crates/ash_sdk/src/protocol.rs
- crates/ash_sdk/tests/conf/custom.yml
- crates/ash_sdk/tests/conf/quicknode.yml
- crates/ash_sdk/tests/conf/wrong.yml
- Fixes #18 
- https://github.com/ava-labs/avalanche-types-rs/pull/36
- _(sdk)_ Use `avalanche_types` structs to deserialize the response from:
- `platform.getSubnets`: `Subnet`
- `platform.getBlockchains`: `Blockchain`
- `platform.getCurrentValidators`: `ApiPrimaryValidator`, `ApiPrimaryDelegator`, and `ApiOwner`
Previously we were using custom implementations
- _(sdk)_ Implement `From` as suggested in #18 for the structs impacted
- _(sdk)_ Add the `get_json_rpc_req_result` method as a generic way of posting a JSON RPC request and getting the result. For that, I had to create the `JsonRpcResponse<Resp, Res>` trait and the `impl_json_rpc_response` macro.
- _(cli)_ Make templating cleaner for validators' info
:warning: For now I am pointing to our fork of `avalanche-types-rs` until the PR …
> Move structs to avalanche_types

- .github/workflows/ci.yml
- crates/ash_cli/src/avalanche/network.rs
- crates/ash_cli/src/avalanche/node.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/src/avalanche/jsonrpc/info.rs
- crates/ash_sdk/src/avalanche/jsonrpc/platformvm.rs
- crates/ash_sdk/src/avalanche/nodes.rs
- Fixes #32
- Fixes #39
- Fixes #40 
- `ash_sdk`
- Use `get_json_rpc_req_result` for all JSON RPC API calls
- Add `get_network_name()` and `is_bootstrapped()` functions in `jsonrpc::info` module
- Store node `public_ip` as `IpAddr` instead of `String`
- Avoid `AvalancheNode.update_info()` failing if the `info.uptime` endpoint returns an error because the node is not a validator
- `ash_cli`
- Add `avalanche node is-bootstrapped` command
- Fix prints templating
- CI
- Enable cache in Actions workflows using `Swatinem/rust-cache@v2`
Still using our fork of `avalanche-types-rs`
> Enrich Avalanche nodes info

- Cargo.lock
- crates/ash_cli/src/avalanche/network.rs
- crates/ash_cli/src/avalanche/node.rs
- crates/ash_cli/src/avalanche/subnet.rs
- crates/ash_cli/src/avalanche/validator.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/Cargo.toml
- crates/ash_sdk/conf/default.yml
- crates/ash_sdk/src/avalanche/jsonrpc/platformvm.rs
- crates/ash_sdk/src/avalanche/nodes.rs
- crates/ash_sdk/src/avalanche/subnets.rs
- crates/ash_sdk/src/lib.rs
- crates/ash_sdk/tests/conf/custom.yml
- crates/ash_sdk/tests/conf/quicknode.yml
- crates/ash_sdk/tests/conf/wrong.yml
- Fixes #42
- `ash_sdk`
- Fix `uptime` field (see https://github.com/ava-labs/avalanche-types-rs/pull/72)
- Add the `subnet_type` field to `AvalancheSubnetValidator` which uses the `AvalancheSubnetType` enum
- Add the `https_enabled` field to `AvalancheNode`
- `ash_cli`
- Improve output templating based on Subnet type
- Add the `--https` flag for all `node` subcommands
Still using our fork of `avalanche-types-rs`
> Add Subnet type

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/ash_cli/src/avalanche.rs
- crates/ash_cli/src/avalanche/validator.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/Cargo.toml
- crates/ash_sdk/README.md
- crates/ash_sdk/conf/default.yml
- crates/ash_sdk/src/avalanche.rs
- crates/ash_sdk/src/avalanche/blockchains.rs
- crates/ash_sdk/src/avalanche/jsonrpc/info.rs
- crates/ash_sdk/src/avalanche/jsonrpc/platformvm.rs
- crates/ash_sdk/src/avalanche/nodes.rs
- crates/ash_sdk/src/avalanche/subnets.rs
- crates/ash_sdk/src/avalanche/wallets.rs
- crates/ash_sdk/tests/conf/quicknode.yml
- Fixes #51 
- Fixes #53 
- Fixes #54 
- SDK
- Adapt to changes in https://github.com/ava-labs/avalanche-types-rs/pull/87: fetch all VMs versions + add `rpc_protocol_version` field
- Add `pending_validators` field to `AvalancheSubnet` and add the necessary functions to update it
- Make the `id` field optional for `AvalancheBlockchain` and thus also in the configuration files. This information will be fetched from the P-Chain anyway.
- Update the C-Chain and X-Chain `id` and `vmID` fields on network subnets update
- CLI
- Minor templating improvements
Using a patch for `avalanche-types-rs` while waiting for https://github.com/ava-labs/avalanche-types-rs/pull/87 to be merged.
> Fetch pending validators

- .cargo/config.toml
- README.md
- scripts/build.sh
- scripts/build_linux.sh
- scripts/build_macos.sh
- scripts/osxcross_setup.sh
- Add Bash scripts to build releases, and archive + hash them. We support building for Linux (current dev OS) and MacOS (thanks to [osxcross](https://github.com/tpoechtrager/osxcross)).
Use `osxcross_setup.sh` to install osxcross locally. We need to build for MacOS AMD64 (before M1) and ARM64 (after M1).
Rust targets mapping:
- `x86_64-apple-darwin` -> AMD64
- `aarch64-apple-darwin` -> ARM64
> feat: add build scripts for Linux and MacOS

- .github/workflows/ci.yml
- crates/ash_cli/src/avalanche/subnet.rs
- crates/ash_cli/src/avalanche/validator.rs
- crates/ash_cli/src/avalanche/vm.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/src/avalanche.rs
- crates/ash_sdk/src/avalanche/vms.rs
- crates/ash_sdk/tests/genesis/subnet-evm.json
- Fixes #57
- Support encoding genesis data for `Custom` VMs. In this case, we just encode the JSON to bytes without parsing.
- Add the `vm generate-id` command to easily generate a VM ID from the VM name as a string.
> Custom VMs genesis data encoding

- Cargo.lock
- Cargo.toml
- crates/ash_cli/Cargo.toml
- crates/ash_cli/src/avalanche.rs
- crates/ash_cli/src/avalanche/blockchain.rs
- crates/ash_cli/src/avalanche/network.rs
- crates/ash_cli/src/avalanche/node.rs
- crates/ash_cli/src/avalanche/subnet.rs
- crates/ash_cli/src/avalanche/validator.rs
- crates/ash_cli/src/avalanche/vm.rs
- crates/ash_cli/src/avalanche/wallet.rs
- crates/ash_cli/src/avalanche/x.rs
- crates/ash_cli/src/conf.rs
- crates/ash_cli/src/main.rs
- crates/ash_cli/src/utils.rs
- crates/ash_sdk/Cargo.toml
- scripts/build_linux.sh
- scripts/build_macos.sh
- Use the `--version` output to provide information on whether a command triggers a transaction. This takes the form of `tx_cmd=(true|false)`. Example with the `avalanche subnet create` command:
```bash
$ ash avalanche subnet create --version
ash_cli-avalanche-subnet-create 0.2.3-alpha.1 (tx_cmd=true)
```
- Support `alpha|beta` versions in build scripts
I did not find any easier way to add metadata around a command, the goal being to ease maintenance on dependant tools like the Ansible Avalanche Collection. IMO this is pretty acceptable for now as we don't make any usage of `--version` at the command level.
> feat(cli): add tx_cmd info to version output

- .cargo/config.toml
- Cargo.lock
- crates/ash_sdk/Cargo.toml
- scripts/build_linux.sh
- scripts/build_macos.sh
- Add build for `linux-arm64` machines
We have to build for ARM64 Linux targets because Multipass VMs on Mac M1 share this architecture with the host. See https://github.com/AshAvalanche/ansible-avalanche-collection/issues/96
> ci: add build for Linux ARM64

- Cargo.lock
- Cargo.toml
- crates/ash_cli/Cargo.toml
- crates/ash_cli/src/avalanche.rs
- crates/ash_cli/src/avalanche/subnet.rs
- crates/ash_cli/src/avalanche/validator.rs
- crates/ash_cli/src/avalanche/wallet.rs
- crates/ash_cli/src/avalanche/warp.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/Cargo.toml
- crates/ash_sdk/build.rs
- crates/ash_sdk/contracts/WarpMessenger.json
- crates/ash_sdk/src/avalanche.rs
- crates/ash_sdk/src/avalanche/blockchains.rs
- crates/ash_sdk/src/avalanche/jsonrpc.rs
- crates/ash_sdk/src/avalanche/jsonrpc/info.rs
- crates/ash_sdk/src/avalanche/jsonrpc/subnet_evm.rs
- crates/ash_sdk/src/avalanche/subnets.rs
- crates/ash_sdk/src/avalanche/vms.rs
- crates/ash_sdk/src/avalanche/vms/subnet_evm.rs
- crates/ash_sdk/src/avalanche/vms/subnet_evm/precompiles.rs
- crates/ash_sdk/src/avalanche/vms/subnet_evm/warp.rs
- crates/ash_sdk/src/avalanche/warp.rs
- crates/ash_sdk/src/errors.rs
- crates/ash_sdk/src/lib.rs
- crates/ash_sdk/src/utils.rs
- https://github.com/ava-labs/avalanche-rs/pull/34
`Avalanche Warp Navigator`:
- Add autogenerated `WarpMessenger` contract bindings (from ABI)
- Add structs to decode Avalanche Warp messages. A `WarpMessage` is composed of:
- A `WarpUnsignedMessage`: see [UnsignedMessage](https://github.com/ava-labs/avalanchego/blob/e70a17d9d988b5067f3ef5c4a057f15ae1271ac4/vms/platformvm/warp/unsigned_message.go#L14)
- A `VerifiedWarpMessage`: pre-verified Warp message as it will be parsed on the destination chain
- A status: `Sent` or `Signed(u16)` with the number of signatures
- A list of `WarpMessageNodeSignature` 
- The payload of a `WarpUnsignedMessage` put further be decoded to an `AddressedPayload` (see [AddressedPayload](https://github.com/ava-labs/subnet-evm/blob/309daad20ba17346ae3712c96c2db594e …
> Avalanche Warp Navigator

- Cargo.lock
- crates/ash_cli/Cargo.toml
- crates/ash_cli/src/avalanche.rs
- crates/ash_cli/src/console.rs
- crates/ash_cli/src/console/auth.rs
- crates/ash_cli/src/main.rs
- crates/ash_cli/src/utils.rs
- crates/ash_sdk/Cargo.toml
- crates/ash_sdk/conf/default.yml
- crates/ash_sdk/src/conf.rs
- crates/ash_sdk/src/console.rs
- crates/ash_sdk/src/console/oauth2.rs
- crates/ash_sdk/src/errors.rs
- crates/ash_sdk/src/lib.rs
- https://github.com/AshAvalanche/jeeo/pull/20
- SDK
- Add `console` module. For now, it only contains configuration loading logic.
- Add `ashConsole` to the default configuration:
```yaml
ashConsole:
apiUrl: http://localhost:8080
oauth2: {...}
```
- Add `console::oauth2` module that allows authenticating to an OAuth2 server. 2 flows have been implemented: authorization code and device code
- CLI
- Add the `console auth` subcommand with `login`, `status`, `logout`, `show-token`, and `refresh-token` commands to demonstrate the authentication flow (device code)
- How to test the new features:
```sh
cargo run -- console auth login
cargo run -- console auth status
cargo run -- console auth show-token --json | jq
cargo run -- console auth refresh-token
carfo run -- console auth logout
```
- …
> Ash Console authentication

- Cargo.lock
- crates/ash_cli/Cargo.toml
- crates/ash_cli/src/avalanche/node.rs
- crates/ash_cli/src/console/secret.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/Cargo.toml
- crates/ash_sdk/src/avalanche/nodes.rs
- https://github.com/AshAvalanche/jeeo/pull/24
- CLI
- Display secret `usedBy` info (number of times the secret is used)
- Add `avalanche node generate-id` command that generates a new Node ID with its TLS cert + key pair. ECDSA is used when possible.
- Support providing `nodeCert` and `nodeKey` as paths when creating a `nodeId` secret. E.g.
```bash
NODE_ID=$(ash avalanche node generate-id -o target/staking --json | jq -r '.nodeID')
ash console secret create "{\"name\": \"Ash NodeID 1\", \"secretType\": \"nodeId\", \"nodeId\": \"${NODE_ID}\",
\"nodeCert\": \"target/staking/node.crt\", \"nodeKey\": \"target/staking/node.key\"}"
```
- On MacOS ARM64 (M1/M2), certificates are generated using RSA. See https://github.com/gyuho/cert-manager/blob/1b4211e1606ebfff6d958ba8a6a726fec03db232/src/x509. …
> Node ID generation

- Cargo.lock
- crates/ash_cli/Cargo.toml
- crates/ash_cli/src/console.rs
- crates/ash_cli/src/console/auth.rs
- crates/ash_cli/src/console/project.rs
- crates/ash_cli/src/console/region.rs
- crates/ash_cli/src/console/secret.rs
- crates/ash_cli/src/utils.rs
- crates/ash_cli/src/utils/prompt.rs
- crates/ash_cli/src/utils/state.rs
- crates/ash_cli/src/utils/templating.rs
- https://github.com/AshAvalanche/jeeo/pull/33
- CLI
- Rename `console ... show` subcommands to `console ... info` out of coherence with `avalanche` commands
- Add `show` and `select` subcommands to `console project`. This allows to select the current project that will be used by default in other subcommands like `console region ...`
```bash
cargo run -- console project show
cargo run -- console project select $PROJECT_ID
cargo run -- console project show
```
- Add the `Cloud regions` column to the `console project` subcommands output table
- Add the `console region` subcommands: `available`, `list`, `add`, `info`, `remove`
```bash
cargo run -- console region available
cargo run -- console region add '{"cloudProvider": "aws", "region": "us-east-2", "cloudCredentialsSecretId": …
```
> feat(cli): console region subcommands

- crates/ash_cli/src/console.rs
- crates/ash_cli/src/console/project.rs
- crates/ash_cli/src/console/resource.rs
- crates/ash_cli/src/utils/templating.rs
- https://github.com/AshAvalanche/hai/pull/37
- https://github.com/AshAvalanche/jeeo/pull/48
- CLI
- Add `console resource` subcommands: `list`, `create`, `info`, `update`, and `delete`
- The `update` subcommand will always fail since the update endpoint isn't implemented in `jeeo`
> feat(cli): add ash console resource subcommands

- Cargo.lock
- crates/ash_sdk/Cargo.toml
- https://github.com/AshAvalanche/jeeo/pull/100
- https://github.com/AshAvalanche/ash-api-rs/pull/2
- Update `ash-api-rs`
> feat: bump ash-api-rs to v0.1.2

- crates/ash_cli/src/console.rs
- crates/ash_cli/src/console/helper.rs
- crates/ash_cli/src/console/resource.rs
- crates/ash_cli/src/utils/templating.rs
- CLI
- Add the `console helper` subcommand. For now, it only has the `stake` command that prompts instructions to stake on an `avalancheNode` resource
- Enrich the table prompts for console subcommands
- For projects: add the number of resources for each type
- For resources: display the cloud region name instead of its ID
How to use:
```bash
$ ash console helper stake avalanche-node-01
1. Navigate to the Core 'Stake/Validate' wizard at https://test.core.app/stake/validate/
2. Select the staking amount
3. Provide the following Node ID: NodeID-JYPvM3Z3f3hpJCQZneBX7kygK5GEyVfqx
4. Complete the 'Stake/Validate' form and sign the transaction!
```
In the future, we can imagine a `helper rpc` command for `avalancheSubnet` resources that prompts the blockchains' RPC endpoints information.
> feat(cli): add console helper subcommand

- crates/ash_cli/src/avalanche/node.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/src/avalanche/jsonrpc/info.rs
- crates/ash_sdk/src/avalanche/nodes.rs
- crates/ash_sdk/src/errors.rs
- SDK
- Store the node BLS proof of possession retrieved from the `info` API as `signer`. See [info.getNodeID](https://docs.avax.network/reference/avalanchego/info-api#infogetnodeid)
- Allow to generate a new BLS private (or secret) key
- CLI
- Add `avalanche node` subcommands: `pop-from-bls-key` and `generate-bls-key` that behave like `id-from-cert` and `generate-id`
> feat: add support for node BLS key and pop

- Cargo.lock
- crates/ash_cli/src/console/resource.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/Cargo.toml
- Fix #84 
- https://github.com/AshAvalanche/ash-api-rs/pull/4
- Just followed the `TODO` instructions to enable support for other resource 
- The table for the `AvalancheSubnet` resource type could use some improvements
- I don't know what I missed but `ash console resource create '{ "name": "my-subnet-evm", "resourceType": "avalancheSubnet",[...]` fails with:
```
Error parsing resource JSON: resourceType: unknown variant `avalancheSubnet`, expected `avalancheNode` at line 3 column 19
```
`resource list` and `resource info` on `AvalancheSubnet` resources works fine tho
> feat: avalanche subnet support

- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/src/avalanche/wallets.rs
- Add HEX and CB58 private keys on the wallet info template.
- Update the struct and impl of AvalancheWalletInfo.
> feat(wallet info): add both HEX and CB58 private key to the template.

- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/src/avalanche/blockchains.rs
- crates/ash_sdk/src/avalanche/txs/p.rs
- crates/ash_sdk/src/avalanche/vms/subnet_evm.rs
- crates/ash_sdk/src/avalanche/wallets.rs
- Update evm id in subnet_evm.rs
- Use its ref in tests instead of hard coding.
> Subnet evm id update

- Cargo.lock
- Cargo.toml
- crates/ash_cli/Cargo.toml
- crates/ash_cli/src/avalanche/blockchain.rs
- crates/ash_cli/src/avalanche/subnet.rs
- crates/ash_cli/src/avalanche/validator.rs
- crates/ash_cli/src/avalanche/wallet.rs
- crates/ash_cli/src/avalanche/x.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/src/avalanche/nodes.rs
- crates/ash_sdk/src/avalanche/subnets.rs
- crates/ash_sdk/src/avalanche/txs/p.rs
- Fixes #87 
- SDK
- Use `add_permissionless_validator` instead of `add_validator` (deprecated in Durango)
- CLI
- Add the `signer` and `signer-format` parameters to the `avalanche validator add` subcommand
- `signer` is required when adding a node as validator to the Primary Network
> feat: use AddPermissionlessValidatorTx

- Cargo.lock
- Cargo.toml
- crates/ash_cli/Cargo.toml
- crates/ash_cli/src/avalanche.rs
- crates/ash_cli/src/avalanche/subnet.rs
- crates/ash_cli/src/avalanche/validator.rs
- crates/ash_cli/src/utils/parsing.rs
- crates/ash_sdk/src/avalanche.rs
- crates/ash_sdk/src/avalanche/jsonrpc/platformvm.rs
- delete every notion of pending validators 
- fit the need of the new AvalancheGo 1.11.3 version 
This is the v0.4.3-rc.1 tag release. When merged, we'll need to update the version of the release to 0.4.3.
> Delete pending validators

- Cargo.lock
- crates/ash_cli/src/console/helper.rs
- crates/ash_cli/src/utils/templating.rs
- crates/ash_sdk/Cargo.toml
- https://github.com/AshAvalanche/ash-rs/issues/95
- Add helper for blockscout
- Add template for blockscout
> feat(blockscout): add blockscout resource creation

- crates/ash_cli/src/avalanche/node.rs
- Use `s` instead of `c` short arg for cert on `ash avalanche node id-from-cert` cmd
> fix(cli): change node cert short arg from c to s
